version: '3'
services:
  node:
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/usr/local/apps/node/dev
      - ignore:/usr/local/apps/node/dev/node_modules/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URL: "mongo"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  redis:
    image: redis:alpine3.16
    ports:
      - "6379:6379"
    volumes:
      - redis:/data/db
volumes:
 mongodb:
 redis:
 ignore: