apiVersion: "v1"
kind: "Service"
metadata: 
  name: "mongo-app"
  labels: 
    app: "mongo-app"
spec: 
  selector:
    app: "mongo-app"
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 30332
  type: "NodePort"