apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo
        env:
        - name: MONGO_URL
          value: "192.168.64.7"
        - name: MONGO_PORT
          value: "30332"
        command: ["mongod", "--bind_ip_all"]
        resources:
          limits:
            cpu: "512m"
            memory: "512m"
        ports:
        - name: mongodb-port
          containerPort: 27017
          protocol: TCP