apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-app
spec:
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - name: mongo-app
        image: mongo
        command:
        - mongod
        - "--bind_ip_all"
        ports:
        - name: mongodbport
          containerPort: 30332
          protocol: TCP